# Generated by Django 4.1.4 on 2022-12-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default=1, upload_to='profile/pic/'),
            preserve_default=False,
        ),
    ]
