# Generated by Django 4.1.4 on 2022-12-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_date_of_birth_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(upload_to='profile/pic/', verbose_name='Your Photo'),
        ),
    ]
